### PR TITLE
Update rf64_parser.py

### PR DESCRIPTION
**Pull request by dannyniu**
Fix a error with formula used in 64-bit chunk size table offset.

### CODE REVIEW

**Comment by iluvcapra** [comment]
I've turned on tests for this branch, thank you for the addition. Can you please provide a test WAV file that exercises this new code?

**Comment by dannyniu** [comment]
While I'm certain that the change is correct, I'm not able to provide any test vector for it. This is because the `data` chunk is likely the *ONLY* chunk in the file that need 64-bit sizes.

I could try make a Dolby Atmos master file with gigantic ADM, but it'll probably be too difficult to send it to you.

**Comment by dannyniu** [comment]
I added a commit to fix a typo. Should be able to pass linting with flake8. But again, my changes are difficult to test because it involve insanely large test vectors.

**Comment by iluvcapra** [comment]
> I added a commit to fix a typo. Should be able to pass linting with flake8. But again, my changes are difficult to test because it involve insanely large test vectors.

I would create a silent test wav flle and then add it as a `.gz` file to the tests/test_files/rf64 directory. At least `tests/test_rf64.py` will hit it and open it, that should cover the code you've added.

**Comment by dannyniu** [comment]
> I would create a silent test wav flle

No use, because we need to test larger-than-4GiB chunks other than `data`, which is what my modification all about. But to do that, I need to produce a non-`data` chunk that's larger than 4GiB, which will be too diffcult to compress and upload.

**Comment by dannyniu** [comment]
@iluvcapra  Is it possible that I simply upload a big file as dummy, so that coverage test will pass even though the newly added code path wasn't reached?

**Comment by RonaldAJ** [comment]
> @iluvcapra Is it possible that I simply upload a big file as dummy, so that coverage test will pass even though the newly added code path wasn't reached?
> 
> Second thought, I'll create a file with non-standard chunks to test it. Right now I'm away from my keyboard, I'll do it when I get back to home.

I checked the large file storage options, but because of the bandwidth limitations it could get quite costly. So I think we can rule that one out.

Other option might be to generate the stream, that is simulate a large file. Not knowing the file format, I don't know how feasible that is.

**Comment by dannyniu** [comment]
I'll be writing a POSIX shell script that generates a over-4GiB-chunks file. It'll be good if you can tell me how to incorporate it into the coverage test. *Or* alternatively, we can decide on some better compression algorithm (e.g. Bzip2, XZ, Zstd, etc.) to upload the file.

**Comment by iluvcapra** [comment]
These files are too big to test it appears.

> tests/test_adm.py ....                                                   [ 14%]
tests/test_cue.py .....                                                  [ 32%]
tests/test_dolby.py .....                                                [ 50%]
tests/test_main.py ...                                                   [ 60%]
tests/test_rf64.py 
Error: The operation was canceled.

I appreciate the contribution but I'm kinda reticent to incorporate support for files that just don't appear in the wild and that we can't practically test within GitHub CI. There might be some other way of testing this change with mocks or virtualizing the test WAVE file, seems like a lot of work though.

**Comment by dannyniu** [comment]
@iluvcapra Fine. If anyone needs large file support, they can come to my fork then.

**Comment by iluvcapra** [comment]
I'll keep thinking about it, it should be possible to test for this with a mock file object it's just more work.

**Comment by dannyniu** [comment]
@iluvcapra In case you're wondering, the next POSIX / Single Unix Specification standard is to include support for "holes" in files - something I've been [following](https://www.austingroupbugs.net/view.php?id=415), although, I'm not sure how much support it has on various platforms.

**Pull request closed without merging**
